### ISSUE TITLE
Reading data from API instead of Twitter Archive

### ISSUE THREAD

**Issue by mateusmaaia** [jollee/expired-tweets#4]
Hi!

I was looking for a way to get the data from public profiles directly from the API, instead of reading local archive, what I wanna know is if you already tried it and had any impediment.

Anyway, I will try and then I open an PR to have the both ways of working, local and API.

Thanks!

**Comment by jolle** [comment]
The Twitter API has some limits for how far back you can look up someone’s tweets from their timeline so it’d be difficult to implement that. In theory, it could be possible to use the search with custom filters to incrementally fetch all the tweets, but that is probably against Twitter’s ToS.

Additionally, looking up someone else’s tweets is in my opinion out of scope for this application as that would greatly increase the possibility of abuse. This tool’s primary purpose is to identify issues in your own timeline and requiring a Twitter tweet archive limits the possibility of abuse quite well.
